---
  jruby_max_runtimes: 1
  extensions:
    resque:
      queues: critical, normal, low 
      count: 100
      path: 'lib/workers' 
      redis_host: 'localhost:6379' 
      work_dir: 'work/resque'
